name = "todo-backend"
main = "worker.js"
compatibility_date = "2024-11-11"

[[kv_namespaces]]
binding = "USERS"
id = "459a1e7fdea545b7ba4356225be886a9"

[[kv_namespaces]]
binding = "TASKS"
id = "394bf65860754fde84903d965dca9276"

[vars]
SECRET_KEY = "your-secret-key-change-this"
ALLOWED_ORIGINS = "https://todo-app.pages.dev,http://localhost:5502"
ADMIN_SECRET_KEY = "admin-secret-2024"
